spring:
  application:
    name: rest-spring-boot-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_rest_api?useTimezone=true&serverTimezone=UTC
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org:
        springframework:
          web: WARN
